### ISSUE TITLE
reStructuredText support for Mote documentation

### ISSUE THREAD

**Issue by CSergienko** [praekelt/mote#33]
The ability to leverage RST to turn the Mote interface into a more powerful tool for writing documentation.

For now, the core functionality this would need to provide is:

- Offload a given pattern's page in the Mote Explorer to RST, enabling more natural documentation and making use of existing functionality like code blocks, etc.
- Custom RST directives, much like those found in Sphynx, for Mote specific functionality, such as the resizable iframe, which will further enable more natural documentation

**Comment by hedleyroos** [comment]
The RST doc must just document the element or variation in question and in isolation, in other words it must not be abused to create hyperlinks to build navigational elements to other elements or variations. I'm fine with us using a link to reference another element on an ad-hoc base. For example, on the button element's RST we may have a discussion around whether you should perhaps be using an anchor, and then link to said anchor element.

**Comment by hedleyroos** [comment]
What is our naming convention for the doc? element.rst? documentation.rst? help.rst?

**Comment by CSergienko** [comment]
@hedleyroos My thinking is that element.rst falls in line with our existing convention.
