### ISSUE TITLE
Add URL flag for beautifying HTML

### ISSUE THREAD

**Issue by CSergienko** [praekelt/mote#36]
One should be able to trigger BeautifulSoup when viewing the Mote Explorer. It should trigger on all the iframe templates with urls like `http://localhost:8000/mote/project/iframe/myproject/browser/templates/home/`

Possibly, this can be done with a URL param such as `?beautify=true`

**Comment by hedleyroos** [comment]
Great idea. Code in develop - will update docs as well.
