### ISSUE TITLE
Iframe template override for multiple Mote projects

### ISSUE THREAD

**Issue by CSergienko** [praekelt/mote#8]
Given that each Mote project will require its own unique setup in the `<head>`, we need a way to have each project have its own iframe template override.

A possible solution may be exposing "project" as a variable in order to do something like this:

```
{% if project = "project-a" %}
    // Load Project A's statics
{% elif project = "project-b" %}
   // Load Project B's statics
{% endif %}
```

**Comment by hedleyroos** [comment]
Feature checked in. In your project directory create `mote/element/iframe.html`.
