### ISSUE TITLE
Iframe template override not applying to variations

### ISSUE THREAD

**Issue by CSergienko** [praekelt/mote#9]
The change as per [this commit](https://github.com/praekelt/mote/commit/17f325f8bb36d29f90874f29d84e322f3e42b8cd) does not appear to work for variations on a pattern, but works fine for the base pattern.

**Comment by hedleyroos** [comment]
@CSergienko fix checked in. Please confirm it works for you.

**Comment by CSergienko** [comment]
Confirmed working. Thank you!
